name: mypaltan
description: "A GetX Counter App with clean architecture."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image: ^4.10.1
  file_picker: ^11.0.3
  url_launcher: ^6.3.2
  flutter_pdfview: ^1.4.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  image_picker_platform_interface: ^2.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Heavy.ttf
          weight: 900
